<?php

return [
    'items' => [
        [
            'slug' => 'flight-disruption-notification',
            'name' => 'Flight Disruption Notification',
            'category' => 'Operations',
            'icon' => 'plane-takeoff',
            'status' => 'Live',
            'accent' => '#38bdf8',
            'blurb' => 'Generate polished customer notices for flight disruptions, hotel services, and car booking changes.',
            'highlight' => 'Copy-ready notices',
            'view' => 'tools.flight-disruption-notification',
        ],
        [
            'slug' => 'meeting-muse',
            'name' => 'Meeting Muse',
            'category' => 'Audio',
            'icon' => 'mic',
            'status' => 'Sketching',
            'accent' => '#38bdf8',
            'blurb' => 'Turn rough meeting notes into tidy recaps, action items, and follow-up drafts.',
            'highlight' => 'Action extraction',
        ],
        [
            'slug' => 'document-lens',
            'name' => 'Document Lens',
            'category' => 'Research',
            'icon' => 'file-text',
            'status' => 'Sketching',
            'accent' => '#f59e0b',
            'blurb' => 'Pull fast summaries, key facts, and risk callouts from long documents and attachments.',
            'highlight' => 'Risk scan',
        ],
        [
            'slug' => 'image-remix',
            'name' => 'Image Remix',
            'category' => 'Visuals',
            'icon' => 'image',
            'status' => 'Sketching',
            'accent' => '#a78bfa',
            'blurb' => 'Generate playful visual variations, alternate styles, and polished concept directions.',
            'highlight' => 'Style swaps',
        ],
        [
            'slug' => 'tone-tuner',
            'name' => 'Tone Tuner',
            'category' => 'Writing',
            'icon' => 'message-square',
            'status' => 'Sketching',
            'accent' => '#34d399',
            'blurb' => 'Rewrite copy for clarity, warmth, confidence, or formality without losing the message.',
            'highlight' => 'Voice matching',
        ],
        [
            'slug' => 'insight-scout',
            'name' => 'Insight Scout',
            'category' => 'Research',
            'icon' => 'search',
            'status' => 'Sketching',
            'accent' => '#fb7185',
            'blurb' => 'Explore themes, patterns, and useful signals across scattered text or feedback.',
            'highlight' => 'Theme clusters',
        ],
        [
            'slug' => 'support-scribe',
            'name' => 'Support Scribe',
            'category' => 'Operations',
            'icon' => 'bot',
            'status' => 'Sketching',
            'accent' => '#60a5fa',
            'blurb' => 'Draft support replies with context-aware suggestions and next-step recommendations.',
            'highlight' => 'Reply drafting',
        ],
        [
            'slug' => 'idea-garden',
            'name' => 'Idea Garden',
            'category' => 'Creation',
            'icon' => 'brain',
            'status' => 'Sketching',
            'accent' => '#22c55e',
            'blurb' => 'Grow a raw thought into angles, names, outlines, and launch-worthy next moves.',
            'highlight' => 'Concept branching',
        ],
    ],
];
